### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by easella** [scheng123/cnn-proxy#7]
![image](https://user-images.githubusercontent.com/74786054/111652545-87280080-87dd-11eb-8233-050fa05a4005.png)

**Comment by binary-person** [comment]
running on repl.it is not supported. also, this isn't a syntax error. `EADDRINUSE` means port is already being used.

and before you ask "how do i fix" i would appreciate it if you at least do some research and refer to my first point about repl.it not being supported
