### ISSUE TITLE
deploy to heroku and syntax error

### ISSUE THREAD

**Issue by easella** [scheng123/cnn-proxy#8]
![image](https://user-images.githubusercontent.com/74786054/111802242-26173000-88a4-11eb-8add-4448f7b442d2.png)
can you make it so I can deploy it to heroku?

**Comment by binary-person** [comment]
I don't plan on supporting heroku. Also, to start things off, that is not even heroku. you're trying to run CNN proxy with react, which will never work.

**Comment by easella** [comment]
then how do I run it? the demo does not work.
![image](https://user-images.githubusercontent.com/74786054/111890194-92398700-89bd-11eb-86ce-807eebe11a12.png)
